name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the server
      - run: |
          echo ${{ secrets.ID_DIGITAL_OCEAN }} &> ~/ssh_key
          ssh -i ~/ssh_key root@168.144.23.95
          cd bms/ && git pull
          pnpm install
          pnpm run build
          pm2 restart web-server
          pm2 restart http-server
          pm2 restart ws-server