name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ secrets.ID_DIGITAL_OCEAN }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no root@168.144.23.95 -t "cd bms/ && git pull origin main && export PATH=/root/.nvm/versions/node/v24.18.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart web-server && pm2 restart http-server && pm2 restart ws-server"
          
          
          
          
          
          